require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccApplicationsController do

  # This should return the minimal set of attributes required to create a valid
  # AccApplication. As you add validations to AccApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccApplicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all acc_applications as @acc_applications" do
      acc_application = AccApplication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:acc_applications).should eq([acc_application])
    end
  end

  describe "GET show" do
    it "assigns the requested acc_application as @acc_application" do
      acc_application = AccApplication.create! valid_attributes
      get :show, {:id => acc_application.to_param}, valid_session
      assigns(:acc_application).should eq(acc_application)
    end
  end

  describe "GET new" do
    it "assigns a new acc_application as @acc_application" do
      get :new, {}, valid_session
      assigns(:acc_application).should be_a_new(AccApplication)
    end
  end

  describe "GET edit" do
    it "assigns the requested acc_application as @acc_application" do
      acc_application = AccApplication.create! valid_attributes
      get :edit, {:id => acc_application.to_param}, valid_session
      assigns(:acc_application).should eq(acc_application)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccApplication" do
        expect {
          post :create, {:acc_application => valid_attributes}, valid_session
        }.to change(AccApplication, :count).by(1)
      end

      it "assigns a newly created acc_application as @acc_application" do
        post :create, {:acc_application => valid_attributes}, valid_session
        assigns(:acc_application).should be_a(AccApplication)
        assigns(:acc_application).should be_persisted
      end

      it "redirects to the created acc_application" do
        post :create, {:acc_application => valid_attributes}, valid_session
        response.should redirect_to(AccApplication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acc_application as @acc_application" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccApplication.any_instance.stub(:save).and_return(false)
        post :create, {:acc_application => {  }}, valid_session
        assigns(:acc_application).should be_a_new(AccApplication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccApplication.any_instance.stub(:save).and_return(false)
        post :create, {:acc_application => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acc_application" do
        acc_application = AccApplication.create! valid_attributes
        # Assuming there are no other acc_applications in the database, this
        # specifies that the AccApplication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccApplication.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => acc_application.to_param, :acc_application => { "these" => "params" }}, valid_session
      end

      it "assigns the requested acc_application as @acc_application" do
        acc_application = AccApplication.create! valid_attributes
        put :update, {:id => acc_application.to_param, :acc_application => valid_attributes}, valid_session
        assigns(:acc_application).should eq(acc_application)
      end

      it "redirects to the acc_application" do
        acc_application = AccApplication.create! valid_attributes
        put :update, {:id => acc_application.to_param, :acc_application => valid_attributes}, valid_session
        response.should redirect_to(acc_application)
      end
    end

    describe "with invalid params" do
      it "assigns the acc_application as @acc_application" do
        acc_application = AccApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => acc_application.to_param, :acc_application => {  }}, valid_session
        assigns(:acc_application).should eq(acc_application)
      end

      it "re-renders the 'edit' template" do
        acc_application = AccApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => acc_application.to_param, :acc_application => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acc_application" do
      acc_application = AccApplication.create! valid_attributes
      expect {
        delete :destroy, {:id => acc_application.to_param}, valid_session
      }.to change(AccApplication, :count).by(-1)
    end

    it "redirects to the acc_applications list" do
      acc_application = AccApplication.create! valid_attributes
      delete :destroy, {:id => acc_application.to_param}, valid_session
      response.should redirect_to(acc_applications_url)
    end
  end

end
